### PR TITLE
🏹 Add Magic Archer

### PR DESCRIPTION
**Pull request by HZooly**
Solves [#100](https://github.com/martincarrera/clash-royale-api/issues/100)

### CODE REVIEW

**Comment by martincarrera** [comment]
Thanks!

**Comment by AmirSavand** [comment]
@martincarrera how is #100 still open?

Oh I think @TorzuoliH should've used `Resolves` keyword instead.

**Comment by AmirSavand** [comment]
tho the issue should remain open, @martincarrera Magic Archer is not in

**Comment by martincarrera** [comment]
That's why the issue is still open, I have to add it manually after the new card is added in the data generator.

**Pull request merged**
